### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by josephgupkim** [jahdroid/codecademy-capstone-project-2-expresso#2]
Your project is working flawlessly and the additional seed data is great.

The only "issue" is that you can't forget to give a unique key to each child in an array.

"Warning: Each child in an array or iterator should have a unique "key" prop."

Although not really a functional issue, it would be helpful to keep in mind!

**Comment by jahdroid** [comment]
I did the "Build Web APIs from Scratch" course, so I only focused on Express.js and SQLite. Therefore the frontend is out of scope for me. But in the future React is on my to-learn-list... ; )
