### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [jahdroid/codecademy-capstone-project-2-expresso#4]
The past couple Expresso projects haven't been meeting the marks so it's refreshing to see a flawlessly functioning Expresso project be submitted!

Great job on the implementation/code for this project but don't forget to tackle all errors in the console and to be mindful of those reading your code (add some comments). Other than that, keep up the awesome work!

Grade: Meets expectation.

**Comment by jahdroid** [comment]
Thanks for reviewing my project and the positive comments : )
